### ISSUE TITLE
Not working on Chrome 64.0.3282.140

### ISSUE THREAD

**Issue by polyphia** [nessgor/mew-gwei-limit#1]
Doesn't seem to do anything on Chrome 64.0.3282.140, just see the grayed out extension icon but it fails to change the slider maximum value to 999, still stuck at 99 .

**Comment by nessgor** [comment]
Please take a look at [this](https://drive.google.com/file/d/1_tbW4wTlnbScISB3yuahB1oGYDX2Kq-Z/view) video and see if it helps. Any suggestion to modify the plugin for better user experience would be appreciated.
